### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by sagy00946** [DeJong-Development/GolfPS-iOS#1]
GolfPS/ApiKeys.plist
GolfPS/GoogleService-Info.plist
GolfPS/Info.plist
GolfPS Widget/Info.plist

these files are missing

**Comment by bubbakanoosh47** [comment]
The Info.plist files are generated when a project is created in Xcode. Edit them as you see fit.

The ApiKeys.plist file contains my own api keys for communicating with the server. Create your own file and insert any api keys that are being referenced in the code to talk to your server instance.

The GoogleService-Info.plist is a Firebase file used to configure communication with a linked firebase project. Spin up your own project and add your own configuration file to the project in its place.

**Comment by weixianpig** [comment]
- What services or APIs are required?
- Can I run the app without Firebase, or are there core features that depend on it?
- Is there a sample or template I can use for `ApiKeys.plist`?
